package consts

// user COMMANDS
const (
	COLLABORATE    = "COLLABORATE"
	INTEGRATE      = "INTEGRATE"
	SUPPORT        = "SUPPORT"
	OTHER          = "OTHER"
	BACK_TO_START  = "BACK_TO_START"
	DESCRIBE_ISSUE = "DESCRIBE_ISSUE"
)

// admin COMMANDS
const (
	BLOCK_USER                     = "BLOCK_USER"
	SHOW_MESSAGES                  = "SHOW_MESSAGES"
	SHOW_MESSAGES_OF_SPECIFIC_USER = "SHOW_MESSAGES_OF_SPECIFIC_USER"
	SHOW_MESSAGES_COUNT_BY_TIME    = "SHOW_MESSAGES_COUNT_BY_TIME"
	DELETE_MESSAGES                = "DELETE_MESSAGES"
	DELETE_MESSAGES_OF_USER        = "DELETE_MESSAGES_OF_USER"
	CHECK_LINKS                    = "CHECK_LINKS"
	SHOW_ALL_OR_NEW_MESSAGES       = "SHOW_ALL_OR_NEW_MESSAGES"
	SELECT_NUMBER_OF_MESSAGES      = "SELECT_NUMBER_OF_MESSAGES"

	SHOW_ALL_MESSAGES = "SHOW_ALL_MESSAGES"
	SHOW_NEW_MESSAGES = "SHOW_NEW_MESSAGES"
)
