package consts

// page names
const (
	INTEGRATION_PAGE = "INTEGRATION_PAGE"
	OTHER_PAGE       = "OTHER_PAGE"
	PARTNERSHIP_PAGE = "PARTNERSHIP_PAGE"
	START_PAGE       = "START_PAGE"
	ADMIN_START_PAGE = "ADMIN_START_PAGE"
	SUPPORT_PAGE     = "SUPPORT_PAGE"
	THANKS_PAGE      = "THANKS_PAGE"
)
