package consts

// page names
const (
	INTEGRATION_PAGE = "INTEGRATION_PAGE"
	OTHER_PAGE       = "OTHER_PAGE"
	PARTNERSHIP_PAGE = "PARTNERSHIP_PAGE"
	START_PAGE       = "START_PAGE"
	SUPPORT_PAGE     = "SUPPORT_PAGE"
	THANKS_PAGE      = "THANKS_PAGE"
)

// admin pages
const (
	ADMIN_START_PAGE                        = "ADMIN_START_PAGE"
	ADMIN_LINKS_PAGE                        = "ADMIN_LINKS_PAGE"
	ADMIN_MSG_COUNT_PAGE                    = "ADMIN_MSG_COUNT_PAGE"
	ADMIN_INPUT_USER_NAME_PAGE              = "ADMIN_INPUT_USER_NAME_PAGE"
	ADMIN_OLD_OR_NEW_MSG_PAGE               = "ADMIN_OLD_OR_NEW_MSG_PAGE"
	ADMIN_LIST_OF_MESSAGES_PAGE             = "ADMIN_LIST_OF_MESSAGES_PAGE"
	ADMIN_LIST_OF_SINGLE_USER_MESSAGES_PAGE = "ADMIN_LIST_OF_SINGLE_USER_MESSAGES_PAGE"
	ADMIN_INFO_AFTER_MSG_DELETION_PAGE      = "ADMIN_INFO_AFTER_MSG_DELETION_PAGE"
)
