package consts

// page names
const (
	INTEGRATION_PAGE = "Links page"
	OTHER_PAGE       = "Something else page"
	PARTNERSHIP_PAGE = "Partnership page"
	START_PAGE       = "Start page"
	SUPPORT_PAGE     = "Support page"
	THANKS_PAGE      = "Thanks page"
	BUG_ISSUE_PAGE   = "Describe bug or issue page"
)

// admin pages
const (
	ADMIN_START_PAGE                        = "ADMIN_START_PAGE"
	ADMIN_LINKS_PAGE                        = "ADMIN_LINKS_PAGE"
	ADMIN_RECEIVED_MSG_COUNT_PAGE           = "ADMIN_RECEIVED_MSG_COUNT_PAGE"
	ADMIN_INPUT_USER_NAME_PAGE              = "ADMIN_INPUT_USER_NAME_PAGE"
	ADMIN_OLD_OR_NEW_MSG_PAGE               = "ADMIN_OLD_OR_NEW_MSG_PAGE"
	ADMIN_LIST_OF_MESSAGES_PAGE             = "ADMIN_LIST_OF_MESSAGES_PAGE"
	ADMIN_LIST_OF_SINGLE_USER_MESSAGES_PAGE = "ADMIN_LIST_OF_SINGLE_USER_MESSAGES_PAGE"
	ADMIN_INFO_AFTER_MSG_DELETION_PAGE      = "ADMIN_INFO_AFTER_MSG_DELETION_PAGE"
	ADMIN_DELETE_MSG_COUNT_PAGE             = "ADMIN_DELETE_MSG_COUNT_PAGE"
	ADMIN_DELETE_MSG_OF_USER_PAGE           = "ADMIN_DELETE_MSG_OF_USER_PAGE"
	ADMIN_SELECT_MSG_COUNT_PAGE             = "ADMIN_SELECT_MSG_COUNT_PAGE"
	ADMIN_SELECT_TIME_FOR_MSG_COUNT_PAGE    = "ADMIN_SELECT_TIME_FOR_MSG_COUNT_PAGE"
	ADMIN_NOTE_AFTER_USER_BLOCK_PAGE        = "ADMIN_NOTE_AFTER_USER_BLOCK_PAGE"
	ADMIN_NOTE_AFTER_USER_UNBLOCK_PAGE      = "ADMIN_NOTE_AFTER_USER_UNBLOCK_PAGE"
)
